/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import org.jivesoftware.smack.XMPPException;
import sources.JabberSmackAPI;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author valentin
 */
public class EnvoiFichier extends javax.swing.JFrame {

    private JabberSmackAPI api;
    private String contact;
    /**
     * Creates new form EnvoiFichier
     */
    public EnvoiFichier(JabberSmackAPI api, String contact) {
        initComponents();
        this.api = api;
        this.contact = contact;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        choixFichier = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        choixFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixFichierActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        getContentPane().add(choixFichier, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixFichierActionPerformed

        try {
            api.fileTransfer(choixFichier.getSelectedFile().getAbsolutePath(),contact);
            this.dispose();
        } catch (XMPPException ex) {
            Logger.getLogger(EnvoiFichier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_choixFichierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser choixFichier;
    // End of variables declaration//GEN-END:variables
}
