/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jivesoftware.smack.XMPPException;
import org.jivesoftware.smack.packet.Presence;
import sources.JabberSmackAPI;

/**
 *
 * @author valentin
 */
public class FenetreAjoutContact extends javax.swing.JFrame {
    
    private JabberSmackAPI api;

    /**
     * Creates new form FenetreAjoutContact
     */
    public FenetreAjoutContact(JabberSmackAPI api) {
        initComponents();
        
        this.api = api;
    }
    
    public void AjoutContact() throws XMPPException{
        
        String id = textFieldIdContact.getText();
        String nom = textFieldNomContact.getText();
        String groupe ;
            
            if (id != null && nom != null){
            api.roster.createEntry(id, nom, null);
            
            Presence subscribe = new Presence(Presence.Type.subscribe);
            subscribe.setTo(id);
            api.connection.sendPacket(subscribe);
            this.dispose();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelIdContact = new javax.swing.JLabel();
        textFieldIdContact = new javax.swing.JTextField();
        labelNomContact = new javax.swing.JLabel();
        textFieldNomContact = new javax.swing.JTextField();
        buttonAjouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajout d'un contact");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelIdContact.setText("Identifiant :");
        getContentPane().add(labelIdContact, new java.awt.GridBagConstraints());

        textFieldIdContact.setText("identifiant du contact");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(textFieldIdContact, gridBagConstraints);

        labelNomContact.setText("Nom :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(labelNomContact, gridBagConstraints);

        textFieldNomContact.setText("nom du contact");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(textFieldNomContact, gridBagConstraints);

        buttonAjouter.setText("Ajouter");
        buttonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjouterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(buttonAjouter, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjouterActionPerformed
        try {
            AjoutContact();
            try {
                api.mesContacts.majPresence();
            } catch (InterruptedException ex) {
                Logger.getLogger(FenetreAjoutContact.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        } catch (XMPPException ex) {
            Logger.getLogger(FenetreAjoutContact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouter;
    private javax.swing.JLabel labelIdContact;
    private javax.swing.JLabel labelNomContact;
    private javax.swing.JTextField textFieldIdContact;
    private javax.swing.JTextField textFieldNomContact;
    // End of variables declaration//GEN-END:variables
}
