/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

/**
 *
 * @author valentin
 */
public class XMPPInfo extends javax.swing.JFrame {

    /**
     * Creates new form XMPPInfo
     */
    public XMPPInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelServeur = new javax.swing.JLabel();
        textFieldServeur = new javax.swing.JTextField();
        labelPort = new javax.swing.JLabel();
        textFieldPort = new javax.swing.JTextField();
        buttonSuivant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelServeur.setText("Serveur");
        getContentPane().add(labelServeur, new java.awt.GridBagConstraints());

        textFieldServeur.setText("monserveur.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(textFieldServeur, gridBagConstraints);

        labelPort.setText("Port");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(labelPort, gridBagConstraints);

        textFieldPort.setText("port du serveur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(textFieldPort, gridBagConstraints);

        buttonSuivant.setText("Suivant");
        buttonSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuivantActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(buttonSuivant, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuivantActionPerformed
        String serveur = textFieldServeur.getText();
        int port = Integer.parseInt(textFieldPort.getText());
        InfoCompte info = new InfoCompte(serveur, port, Session.Xmpp);
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonSuivantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSuivant;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelServeur;
    private javax.swing.JTextField textFieldPort;
    private javax.swing.JTextField textFieldServeur;
    // End of variables declaration//GEN-END:variables
}
